# Generated by Django 6.0.6 on 2026-06-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='Link',
            new_name='link',
        ),
    ]
